### ISSUE TITLE
1.7.10 Issue

### ISSUE THREAD

**Issue by giogimic** [bekvon/Residence#112]
```
[08:28:12 INFO]: GioGimic issued server command: /res select size
[08:28:12 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'res' in plugin Residence v2.8.4.0
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[PluginCommand.class:1.7.10-1492.152]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:181) ~[SimpleCommandMap.class:1.7.10-1492.152]
        at org.bukkit.craftbukkit.v1_7_R4.CraftServer.dispatchCommand(CraftServer.java:717) ~[CraftServer.class:1.7.10-1492.152]
        at net.minecraft.network.NetHandlerPlayServer.func_147361_d(NetHandlerPlayServer.java:1317) [nh.class:?]
        at net.minecraft.network.NetHandlerPlayServer.func_147354_a(NetHandlerPlayServer.java:1099) [nh.class:?]
        at net.minecraft.network.play.client.C01PacketChatMessage.func_148833_a(C01PacketChatMessage.java:38) [ir.class:?]
        at net.minecraft.network.play.client.C01PacketChatMessage.func_148833_a(C01PacketChatMessage.java:53) [ir.class:?]
        at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:244) [ej.class:?]
        at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:173) [nc.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:991) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:431) [lt.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:809) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:669) [MinecraftServer.class:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_51] Caused by: java.lang.NullPointerException
        at com.bekvon.bukkit.residence.ResidenceCommandListener.commandResSelect(ResidenceCommandListener.java:786) ~[?:?]
        at com.bekvon.bukkit.residence.ResidenceCommandListener.commandRes(ResidenceCommandListener.java:254) ~[?:?]
        at com.bekvon.bukkit.residence.ResidenceCommandListener.onCommand(ResidenceCommandListener.java:144) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[PluginCommand.class:1.7.10-1492.152]
        ... 13 more
```

**Comment by Zrips** [comment]
Cant reproduce issue, do you have idea whats caused this? Did you selected area before this happened? are you using world edit?

**Comment by giogimic** [comment]
I Launch the server connect use a wooden pick to try and select nothing happens so i try a hoe still nothing so i tried that command and thats what console says. I just removed all my other plugins with the exception of Residence and tried it same thing. I've been using the 1.6.9 version of Residence (removed the cfgs before trying this one) and haven't really had an issue with it.. I'ts probably because im using kCauldron..

**Comment by Zrips** [comment]
Well yea, as it is not supported, you should get some errors on launch.

**Comment by giogimic** [comment]
Nope no launch errors just usage.. that sucks i really like Residence. So much better than Towny & Factions. I'll close this now i guess.
