### ISSUE TITLE
Issues with WorldEdit: Unable to Pass PlayerInteractEvent, since WorldEdit does not have Class "Vector"

### ISSUE THREAD

**Issue by Alex4386** [bekvon/Residence#145]
Here is detailed StackTrace for Troubleshooting
```
[00:15:56] [Server thread/ERROR]: Could not pass event PlayerInteractEvent to Residence v4.8.3.1
java.lang.NoClassDefFoundError: com/sk89q/worldedit/Vector
        at com.bekvon.bukkit.residence.selection.WorldEdit7SelectionManager.worldEditUpdate(WorldEdit7SelectionManager.java:58) ~[?:?]
        at com.bekvon.bukkit.residence.selection.WorldEdit7SelectionManager.placeLoc1(WorldEdit7SelectionManager.java:72) ~[?:?]
        at com.bekvon.bukkit.residence.listeners.ResidencePlayerListener.onSelection(ResidencePlayerListener.java:1140) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor479.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:70) ~[patched_1.13.2.jar:git-Paper-"b2f6b9f7"]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[patched_1.13.2.jar:git-Paper-"b2f6b9f7"]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[patched_1.13.2.jar:git-Paper-"b2f6b9f7"]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:513) ~[patched_1.13.2.jar:git-Paper-"b2f6b9f7"]
        at org.bukkit.craftbukkit.v1_13_R2.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:315) ~[patched_1.13.2.jar:git-Paper-"b2f6b9f7"]
        at org.bukkit.craftbukkit.v1_13_R2.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:282) ~[patched_1.13.2.jar:git-Paper-"b2f6b9f7"]
        at net.minecraft.server.v1_13_R2.PlayerInteractManager.a(PlayerInteractManager.java:110) ~[patched_1.13.2.jar:git-Paper-"b2f6b9f7"]
        at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:1277) ~[patched_1.13.2.jar:git-Paper-"b2f6b9f7"]
        at net.minecraft.server.v1_13_R2.PacketPlayInBlockDig.a(SourceFile:40) ~[patched_1.13.2.jar:git-Paper-"b2f6b9f7"]
        at net.minecraft.server.v1_13_R2.PacketPlayInBlockDig.a(SourceFile:10) ~[patched_1.13.2.jar:git-Paper-"b2f6b9f7"]
        at net.minecraft.server.v1_13_R2.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:12) ~[patched_1.13.2.jar:git-Paper-"b2f6b9f7"]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_191]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_191]
        at net.minecraft.server.v1_13_R2.SystemUtils.a(SystemUtils.java:109) ~[patched_1.13.2.jar:git-Paper-"b2f6b9f7"]
        at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1016) ~[patched_1.13.2.jar:git-Paper-"b2f6b9f7"]
        at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:439) ~[patched_1.13.2.jar:git-Paper-"b2f6b9f7"]
        at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:943) ~[patched_1.13.2.jar:git-Paper-"b2f6b9f7"]
        at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:841) ~[patched_1.13.2.jar:git-Paper-"b2f6b9f7"]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_191]
```

**Comment by ghost** [comment]
Residence's support is very slow and innactive..
