### ISSUE TITLE
Can't load the Residence Plugin. Me not know why.

### ISSUE THREAD

**Issue by SNWCreations** [bekvon/Residence#152]
My Server is Glowstone 1.12.2
OS: Windows 7, 64-bit

Log:
2020/03/06 08:39:44 [ERROR] Error occurred while enabling Residence v4.8.8.2 (Is it up to date?)
java.lang.ExceptionInInitializerError
	at com.bekvon.bukkit.cmiLib.CMIMaterial.get(CMIMaterial.java:1309)
	at com.bekvon.bukkit.residence.ConfigManager.UpdateConfigFile(ConfigManager.java:427)
	at com.bekvon.bukkit.residence.ConfigManager.<init>(ConfigManager.java:269)
	at com.bekvon.bukkit.residence.Residence.getConfigManager(Residence.java:1061)
	at com.bekvon.bukkit.residence.Residence.onEnable(Residence.java:495)
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:316)
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:411)
	at net.glowstone.GlowServer.enablePlugins(GlowServer.java:966)
	at net.glowstone.GlowServer.start(GlowServer.java:630)
	at net.glowstone.GlowServer.run(GlowServer.java:452)
	at net.glowstone.GlowServer.main(GlowServer.java:322)
Caused by: java.lang.NullPointerException
	at com.bekvon.bukkit.cmiLib.VersionChecker$Version.isCurrentEqualOrLower(VersionChecker.java:144)
	at com.bekvon.bukkit.cmiLib.CMIMaterial.updateMaterial(CMIMaterial.java:1161)
	at com.bekvon.bukkit.cmiLib.ItemManager.<clinit>(ItemManager.java:39)
	... 12 more
2020/03/06 08:39:44 [INFO] Disabling Residence v4.8.8.2
2020/03/06 08:39:44 [ERROR] Error occurred while disabling Residence v4.8.8.2 (Is it up to date?)
java.lang.NoClassDefFoundError: Could not initialize class com.bekvon.bukkit.cmiLib.ItemManager
	at com.bekvon.bukkit.cmiLib.CMIMaterial.get(CMIMaterial.java:1309)
	at com.bekvon.bukkit.residence.ConfigManager.UpdateConfigFile(ConfigManager.java:427)
	at com.bekvon.bukkit.residence.ConfigManager.<init>(ConfigManager.java:269)
	at com.bekvon.bukkit.residence.Residence.getConfigManager(Residence.java:1061)
	at com.bekvon.bukkit.residence.Residence.onDisable(Residence.java:405)
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:266)
	at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:344)
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:320)
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:411)
	at net.glowstone.GlowServer.enablePlugins(GlowServer.java:966)
	at net.glowstone.GlowServer.start(GlowServer.java:630)
	at net.glowstone.GlowServer.run(GlowServer.java:452)
	at net.glowstone.GlowServer.main(GlowServer.java:322)

**Comment by SNWCreations** [comment]
My plugin is lastet version.
