### ISSUE TITLE
Minecraft server crash.

### ISSUE THREAD

**Issue by mckuhei** [bekvon/Residence#158]
```
[11:17:56] [Server thread/INFO] [com.bekvon.bukkit.residence.Residence]: [Residence] Enabling Residence v4.9.3.5
[11:18:03] [Server thread/INFO] []: [Residence] Found Vault, but Vault reported no usable permissions system...
[11:18:03] [Server thread/INFO] []: [Residence] Permissions plugin NOT FOUND!
[11:18:03] [Server thread/INFO] []: [Residence] Scanning for economy systems...
[11:18:03] [Server thread/INFO] []: [Residence] Found Vault using economy: Essentials Economy
[11:18:04] [Server thread/INFO] []: [Residence] Loading save data for world world...
[11:18:04] [Server thread/ERROR] [com.bekvon.bukkit.residence.Residence]: null
java.lang.NullPointerException: null
	at com.bekvon.bukkit.residence.Residence.loadYml(Residence.java:1357) [Residence4.9.3.5.jar:?]
	at com.bekvon.bukkit.residence.Residence.onEnable(Residence.java:659) [Residence4.9.3.5.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) [JavaPlugin.class:git-CatServer-1.12.2-4292748]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:328) [JavaPluginLoader.class:git-CatServer-1.12.2-4292748]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [SimplePluginManager.class:git-CatServer-1.12.2-4292748]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:437) [CraftServer.class:git-CatServer-1.12.2-4292748]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:385) [CraftServer.class:git-CatServer-1.12.2-4292748]
	at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:384) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:327) [nz.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:593) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_144]
[11:18:04] [Server thread/ERROR] [com.bekvon.bukkit.residence.Residence]: [Residence] Unable to load save file
java.lang.NullPointerException: null
	at com.bekvon.bukkit.residence.Residence.loadYml(Residence.java:1357) ~[Residence4.9.3.5.jar:?]
	at com.bekvon.bukkit.residence.Residence.onEnable(Residence.java:659) [Residence4.9.3.5.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) [JavaPlugin.class:git-CatServer-1.12.2-4292748]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:328) [JavaPluginLoader.class:git-CatServer-1.12.2-4292748]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [SimplePluginManager.class:git-CatServer-1.12.2-4292748]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:437) [CraftServer.class:git-CatServer-1.12.2-4292748]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:385) [CraftServer.class:git-CatServer-1.12.2-4292748]
	at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:384) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:327) [nz.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:593) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_144]
[11:18:04] [Server thread/INFO] [com.bekvon.bukkit.residence.Residence]: [Residence] Disabling Residence v4.9.3.5
[11:18:04] [Server thread/INFO] []: [Residence] WorldEdit NOT found!
[11:18:04] [Server thread/INFO] []: [Residence] - FAILED INITIALIZATION! DISABLED! ERROR:
[11:18:04] [Server thread/ERROR] [com.bekvon.bukkit.residence.Residence]: null
java.lang.NullPointerException: null
	at com.bekvon.bukkit.residence.Residence.loadYml(Residence.java:1357) ~[Residence4.9.3.5.jar:?]
	at com.bekvon.bukkit.residence.Residence.onEnable(Residence.java:659) [Residence4.9.3.5.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) [JavaPlugin.class:git-CatServer-1.12.2-4292748]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:328) [JavaPluginLoader.class:git-CatServer-1.12.2-4292748]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [SimplePluginManager.class:git-CatServer-1.12.2-4292748]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:437) [CraftServer.class:git-CatServer-1.12.2-4292748]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:385) [CraftServer.class:git-CatServer-1.12.2-4292748]
	at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:384) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:327) [nz.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:593) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_144]
[11:18:04] [Server thread/ERROR] [Minecraft]: Error occurred while enabling Residence v4.9.3.5 (Is it up to date?)
java.lang.NoClassDefFoundError: com/bekvon/bukkit/cmiLib/VersionChecker$1
	at com.bekvon.bukkit.cmiLib.VersionChecker.VersionCheck(VersionChecker.java:59) ~[?:?]
	at com.bekvon.bukkit.residence.Residence.onEnable(Residence.java:812) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[JavaPlugin.class:git-CatServer-1.12.2-4292748]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:328) [JavaPluginLoader.class:git-CatServer-1.12.2-4292748]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [SimplePluginManager.class:git-CatServer-1.12.2-4292748]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:437) [CraftServer.class:git-CatServer-1.12.2-4292748]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:385) [CraftServer.class:git-CatServer-1.12.2-4292748]
	at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:384) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:327) [nz.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:593) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_144]
Caused by: java.lang.ClassNotFoundException: com.bekvon.bukkit.cmiLib.VersionChecker$1
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:140) ~[PluginClassLoader.class:git-CatServer-1.12.2-4292748]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:108) ~[PluginClassLoader.class:git-CatServer-1.12.2-4292748]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_144]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_144]
	... 11 more
Caused by: java.lang.ClassNotFoundException: com.bekvon.bukkit.cmiLib.VersionChecker$1
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381) ~[?:1.8.0_144]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_144]
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:335) ~[?:1.8.0_144]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_144]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:138) ~[PluginClassLoader.class:git-CatServer-1.12.2-4292748]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:108) ~[PluginClassLoader.class:git-CatServer-1.12.2-4292748]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_144]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_144]
	... 11 more
```
version: 4.9.3.5
Minecraft version:1.12.2

**Comment by loowtime** [comment]
The plugin has a issue ask the developer or deleted it from your server it is not up to date i guess...
